### ISSUE TITLE
What's the difference between "kubernetes-sigs/etcd-manager" and "kubernetes-retired/etcdadm/etcd-manager" ?

### ISSUE THREAD

**Issue by pracan** [kubernetes-sigs/etcd-manager#17]
Hello, few questions :

1) [kubernetes-retired/etcdadm](https://github.com/kubernetes-retired/etcdadm) has been Archived and this repo looks like [kubernetes-retired/etcdadm/tree/master/etcd-manager](https://github.com/kubernetes-retired/etcdadm/tree/master/etcd-manager), so i was wondering how are you two linked ?

2) Do you intend to take over the "etcd-manager" part of the "etcdadm" project ? Or is this just some kind of archive or copy ?

3) Can etcd-manager still be used nowadays (mostly for etcd backup and restore) or would you advise to use something else (like etcdutl or etcdctl) ?

Sorry if it isn't the right place to post this

**Comment by hakman** [comment]
Hi @pracan, etcd-manager was always a separate project mostly used in kOps. Initially we considered that etcdadm would be a good home, but later decided on a dedicated repo. As you can see from the commits, the project is alive and well.
I am not sure about the future of backup and restore.

**Comment by pracan** [comment]
I understand it better now. Thanks for your help !
